# permissions for end users to view drwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drwatcher-viewer-role
rules:
- apiGroups:
  - dr.seven
  resources:
  - drwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dr.seven
  resources:
  - drwatchers/status
  verbs:
  - get
