name: quay

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build master
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run make envtestbin
      run: make envtestbin
      env:
        GO111MODULE: on
        GOOS: linux
        GOARCH: amd64

    - name: Run make test
      run: make test
      env:
        GO111MODULE: on
        GOOS: linux
        GOARCH: amd64

    - name: Send result to coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

    - uses: actions/upload-artifact@v2
      with:
        name: drwatcher-operator
        path: build/bin/drwatcher-operator
        if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_ROBOT_TOKEN }}
